### ISSUE TITLE
[OEP-55] 20/04 - 04/05

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/openedx-filters#81]
## Description
Ticket to keep track of the work done around the maintainers pilot.

## Tasks
- [x] Add dependabot, example PR: https://github.com/openedx/docs.openedx.org/blob/main/.github/dependabot.yml
- [x] Add CODEOWNERs as POC
- [ ] Keep writing documentation @mariajgrimaldi 
- [ ] Open ticket to Axim to deploy readthedocs
- [ ] Review PR https://github.com/openedx/openedx-filters/pull/77

**Comment by mariajgrimaldi** [comment]
Hi @felipemontoya, please feel free to assign yourself any of the pending tasks. Thanks!

**Comment by mariajgrimaldi** [comment]
Leftovers for the next 2 weeks: 

- [ ] Keep writing documentation @mariajgrimaldi 
- [ ] Open ticket to Axim to deploy readthedocs
- [ ] Review PR https://github.com/openedx/openedx-filters/pull/77
