### ISSUE TITLE
Aid adoption of openedx-filters

### ISSUE THREAD

**Issue by kdmccormick** [openedx/openedx-filters#91]
### Background

Adoption of robust plugin systems, notably openedx-filters and openedx-events, is critical for both:
* the long-term maintainability of edx-platform, and
* the businesses which rely on Open edX as a platform for their solutions.

2U has recently begun trying out openedx-filters as a way to address their business needs without coupling their business logic with edx-platform. For context, see [the discussion on this PR](https://github.com/openedx/edx-platform/pull/32275).

### To do

2U engineers have highlighted some challenges they see in adopting openedx-filters. We want to unblock them in the short-term, while also paving the way for other teams to build using openedx-filters in the near future. Let's collect the problems and delegate here.

```[tasklist]
### Immediate needs / reviews
- [ ] https://github.com/openedx/openedx-filters/pull/90
- [ ] https://github.com/openedx/edx-platform/pull/32294
```
```[tasklist]
### Next steps
- [ ] Document OPEN_EDX_FILTERS_CONFIG in edx-platform common settings
- [ ] Link to hooks docs from openedx-filters and openedx-events READMEs
- [ ] More docs for using openedx-filters in practice
- [ ] Design discussion: Are filters appropriate for single function replacement?
- [ ] Education: Add links to relevant videos
- [ ] Education: Host Hooks workshop?
- [ ] Explanation of Hooks Plugins vs. old-style plugins
```

**Comment by kdmccormick** [comment]
This was done to a varying degree by several people, and various organizations including 2U are making frequent use of openedx-events and openedx-filters for plugins now.
